django-polls/polls/urls.py
from django.urls import path

from . import views


# Set the application namespace.
# E.g. for {% url %} pointing to path named 'detail',
#      we do {% url 'polls:detail' %} instead.
app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

django-polls/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    text = models.CharField(max_length=200)
    publication_date = models.DateTimeField('Publication Date')

    def was_published_recently(self):
        now = timezone.now()
        recency_threshold = now - datetime.timedelta(days=1)
        was_published = self.publication_date <= now
        is_recent = self.publication_date >= recency_threshold
        return was_published and is_recent
    was_published_recently.admin_order_field = 'publication_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = "Published recently?"

    def __str__(self):
        return self.text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.text

django-polls/polls/views.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import Http404
from django.urls import reverse
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.views import generic
from django.utils import timezone

from .models import Question
from .models import Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_questions'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
            publication_date__lte=timezone.now()
        ).order_by('-publication_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """Excludes any questions that aren't published yet."""
        return Question.objects.filter(publication_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404(f"Question {question_id} does not exist")
    try:
        choice_id = request.POST['choice']
        selected_choice = question.choice_set.get(pk=choice_id)
    except KeyError:
        context = {
            'question': question,
            'error_message': "You didn't select a choice.",
        }
        response = render(request, 'polls/detail.html', context)
    except Choice.DoesNotExist:
        context = {
            'question': question,
            'error_message': f"Choice {choice_id} does not exist.",
        }
        response = render(request, 'polls/detail.html', context)
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return HttpResponseRedirect after a successful POST
        response = HttpResponseRedirect(
            reverse('polls:results', args=(question.id,)))
    return response

django-polls/polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Question Details</title>
</head>
<body>
    <h1>{{ question.text }}</h1>
    {% if error_message %}
    <p>
        <strong>{{ error_message }}</strong>
    </p>
    {% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input
            type="radio"
            name="choice"
            id="choice{{ forloop.counter }}"
            value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">
            {{ choice.text }}
        </label>
        <br />
    {% endfor %}
    <input type="submit" value="Vote" />
    </form>
</body>

django-polls/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Polls</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
</head>
<body>
{% if latest_questions %}
    <ul>
    {% for question in latest_questions %}
        <li>
            <a href="{% url 'polls:detail' question.id %}">
                {{ question.text }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

django-polls/polls/templates/polls/results.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <title>Poll Results</title>
</head>
<body>
    <h1>{{ question.text }}</h1>
    
    <ul>
    {% for choice in question.choice_set.all %}
        <li>
            {{ choice.text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
        </li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">
        Vote again?
    </a>
</body>
</html>